# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-27 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durgasoftapp', '0003_enquirydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirydata',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
